version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27014:27021"
    command: ["mongod", "--port", "27021"]
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
